Cleanup clang compiler warnings
epics-base/pva2pva pull request #63
Opened 2024-08-07 19:58 UTC by anjohnson

After these changes there's only one build warning left from pva2pva builds with Clang 15.0 on macOS, a deprecation warning for `epicsThreadExitMain()` which I deliberately left in. I removed the other deprecation warnings because they are in test files that apparently check the deprecated API.

I had to update the .ci module to various targets to build, but I didn't get around to removing the CentOS-7 build so that still dies.

2024-08-07 23:07 UTC, anjohnson commented
It looks like the ci update that I did may need some Appveyor config changes; any advice on that would be welcome (I haven't checked the ci-scripts release notes yet). The vs2019 builds all fail immediately like this, but both vs2015 and vs2017 builds succeed:
```
Build started
git config --global core.autocrlf true
git clone -q --depth=50 https://github.com/epics-base/pva[2](https://ci.appveyor.com/project/mdavidsaver/pva2pva/builds/50365445/job/a7npfywh2mocqfq5#L2)pva.git C:\projects\pva2pva
git fetch -q origin +refs/pull/6[3](https://ci.appveyor.com/project/mdavidsaver/pva2pva/builds/50365445/job/a7npfywh2mocqfq5#L3)/merge:
git checkout -qf FETCH_HEAD
Restoring build cache
Cache 'C:\Users\appveyor\.tools' - Restored
Running Install scripts
cinst re2c
'cinst' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
Get-ChildItem *.tap -Recurse -Force | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
python .ci/cue.py build test-results -s
python: can't open file 'C:\\projects\\pva2pva\\.ci\\cue.py': [Errno 2] No such file or directory
Command exited with code 2
```

2024-08-09 05:45 UTC, ralphlange commented
`cinst` is the Chocolatey installer.

By all means, that should be available on the GHA Windows runners.

2024-08-12 05:05 UTC, anjohnson commented
I think this PR is ready to go now, unless we also want to suppress the deprecation warning for the `epicsThreadExitMain()` call in `softIocPVA`'s `main()` function.

2024-08-13 23:45 UTC, mdavidsaver requested changes

2024-08-13 23:45 UTC, mdavidsaver commented on p2pApp/gwmain.cpp
> +namespace p2pgw {
How is this causing a warning?

Anonymous namespace date to C++98.  This is the c++ equivalent of static functions, also effecting special symbols for classes.

2024-08-13 23:47 UTC, mdavidsaver commented on p2pApp/gwmain.cpp
> +namespace p2pgw {
Strictly speaking symbols in an anonymous namespace were not [specified](https://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces) to have until c++11, but in practice clang, gcc, and msvc have done so for many years.

2024-08-14 17:46 UTC, anjohnson commented on p2pApp/gwmain.cpp
> +namespace p2pgw {
Right, they're supported but annoyingly warned about:
```
../gwmain.cpp:245:57: warning: non-type template argument referring to function 'iocsh_drop' with internal linkage is a C++11 extension [-Wc++11-extensions]
        epics::iocshRegister<const char*, const char*, &iocsh_drop>("drop", "client", "channel");
                                                        ^~~~~~~~~~
../gwmain.cpp:205:6: note: non-type template argument refers to function here
void iocsh_drop(const char *client, const char *channel)
     ^
```
This PR is about cleaning up compiler warnings, and on macOS with Clang-15 I'm getting several of the above from both gwmain.cpp and qsrv.cpp.

An alternative approach would be to turn off those `c++11-extensions` warnings, preferably in the Base build configuration files. The following local PoC works for me, but it would have to be compiler-specific, maybe even dependent on the GCC & Clang versions:
```patch
diff --git a/p2pApp/Makefile b/p2pApp/Makefile
index 602518b..6a27152 100644
--- a/p2pApp/Makefile
+++ b/p2pApp/Makefile
@@ -6,6 +6,7 @@ include $(TOP)/configure/CONFIG
 #=============================
 
 USR_CPPFLAGS += -I$(TOP)/common
+USR_CXXFLAGS += -Wno-c++11-extensions
 
 PROD_HOST = p2p
 
```

2025-02-26 17:47 UTC, anjohnson commented
Rebased to only include the clang warning changes (I'd forgotten this already had a PR!).

2026-03-06 17:23 UTC, anjohnson commented
Rebased, removed namespace mod's and `epicsThreadExitMain()`, added `OVERRIDE FINAL`

2026-03-06 19:42 UTC, anjohnson commented
I will rebase this onto a branch that fixes the CI, currently waiting for

- [this Appveyor job](https://ci.appveyor.com/project/anjohnson/pva2pva/builds/53654925)
- [these GitHub actions](https://github.com/anjohnson/pva2pva/actions/runs/22775214378)

2026-03-06 23:28 UTC, anjohnson commented on p2pApp/gwmain.cpp
> +namespace p2pgw {
Removed my namespace changes, newer Clang no longer warns about the originals.

2026-03-07 15:17 UTC, mdavidsaver approved these changes
Looks ok.

2026-03-09 17:07 UTC, anjohnson commented
Thanks. I realized over the weekend that pva2pva's GitHub CI jobs are still configured for the no-longer-supported Ubuntu-20, which is why they aren't running here. I'll fix that too.

At least I got Appveyor to [pass](https://ci.appveyor.com/project/anjohnson/pva2pva/builds/53659005) my [update-ci branch](https://github.com/anjohnson/pva2pva/tree/update-ci) over the weekend.

2026-03-11 15:04 UTC, merged